### ISSUE TITLE
Script hangs randomly. Have to unplug to re-initialize.

### ISSUE THREAD

**Issue by cellrok** [git-moss/APCmini4Bitwig#3]
I don't know what is causing this. After using it for a while, even if it is just for selecting tracks and launching clips, it hangs. This means the controller isn't updated anymore and will show the last state it was in until you turn it off (unplug).

Maybe someone else has this problem? Is it known?

**Comment by git-moss** [comment]
I know what you mean. My impression it that the problem is the hardware itself. I simply stopped using the device. It seems to me that it is only designed to take a small amount of midi messages to do the clip launching and crashes in other situations.
I will leave that issue open as an information to other users and close your other issues which have all the same root problem.

**Comment by git-moss** [comment]
Can't do anything about it.
